project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!solutions/"
    - "!backlog/"

website:
  title: "Analysis of Ecological Data"
  sidebar:
    collapse-level: 0
    style: "docked"
    alignment: left
    border: true
    contents:
      - section: "Basics"
        contents:
        - "D01_data_examples.qmd"
        - "B01_intro_R.qmd"
        - "R02_basics.qmd"
        - "R03_vectors.qmd"
        - "R04_logic.qmd"
        - "assignments/Ex01_first.qmd"
        - "assignments/Ex02_second.qmd"
      - section: "Data handling"
        contents:
      # - "D02_projects_io.qmd"
        - "df01_introduction.qmd"
        - "df02_files.qmd"
        - "df03_tidyverse.qmd"
      #   - "R06_long_wide.qmd"
        - "assignments/Ex03_iris.qmd"
        - "assignments/Ex04a_trees.qmd"
        - "assignments/Ex04b_trees_tidyverse.qmd"
      #   - "E06_german_climate.qmd"
      # - section: "Utility \n & Applications"
      #   contents: 
      #   - "R06_strings.qmd"
      #   - "R07_lists.qmd"
      #   - "R08_formula.qmd"
      #   - "R09_linearmodels.qmd"
      #   - "E08_feldfruechte_arthropoden.qmd"
      #   - "E07_lm.qmd"
      #   - "E09_biodiversity.qmd"
      # - section: "Graphics"
      #   contents:
      #   - "R10_ggplot.qmd"
      #   - "R11_markdown.qmd"
      #   - "E09_ggplot.qmd"
      #   - "E10_markdown.qmd"
      - section: "Appendix"
        contents:
        - "98-additional_resources.Rmd"
    
bibliography: "../../literature/zotero/references.bib"
number-depth: 0
format:
  html:
    theme: 
      light: flatly
      dark: superhero
    number-sections: false
    grid:
      sidebar-width: 350px
execute: 
  warning: false
  message: false

metadata-files:
  - _revealjs.yml
