project:
  type: book
  output-dir: docs


book:
  title: "Analysis of Ecological Data"
  author: "Marvin Ludwig"
  chapters:
    - "index.Rmd"
    - "D01_data_examples.Rmd"
    - "R01_introduction.qmd"
    - "R02_basics.qmd"
    - "R03_vectors.qmd"
    - part: "Exercises"
      chapters:
      - "exercise/E01-variablen.Rmd"
  appendices:
  - "98-additional_resources.Rmd"
  - "references.qmd"
  favicon: "/home/marvin/images/pictogramms/ecoR.svg"
    
bibliography: "/home/marvin/literature/zotero/references.bib"
number-depth: 0
format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt
execute: 
  warning: false
  message: false


