project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!solutions/"
    - "!backlog/"

website:
  title: "Analysis of Ecological Data"
  sidebar:
    collapse-level: 0
    style: "docked"
    alignment: left
    border: true
    contents:
      - section: "Basics"
        contents:
        - "D01_data_examples.qmd"
        - "B01_intro_R.qmd"
        - "R02_basics.qmd"
        - "R03_vectors.qmd"
        - "R04_logic.qmd"
        - "assignments/Ex01_first.qmd"
        - "assignments/Ex02_second.qmd"
      - section: "Data handling"
        contents:
      # - "D02_projects_io.qmd"
        - "df01_introduction.qmd"
        - "df02_files.qmd"
        - "df03_tidyverse.qmd"
        - "df04_wide_long.qmd"
        - "assignments/Ex03_iris.qmd"
        - "assignments/Ex04a_trees.qmd"
        - "assignments/Ex04b_trees_tidyverse.qmd"
      - section: "Data analysis"
        contents: 
        - "assignments/Ex05_german_climate.qmd"
        - "assignments/Ex06_cropspecies.qmd"
      #   - "R06_strings.qmd"
      #   - "R07_lists.qmd"
        - "R08_formula.qmd"
        - "R09_linearmodels.qmd"
        - "assignments/Ex07_species_area.qmd"
      #   - "E09_biodiversity.qmd"
      - section: "Graphics"
        contents:
        - "vis01_ggplot.qmd"
        - "vis02_ggplot_advanced.qmd"
        - "vis03_markdown.qmd"
        - "assignments/Ex08_ggplot.qmd"
        - "assignments/Ex09_markdown.qmd"
      - section: "Appendix"
        contents:
        - "wheretogo.qmd"
        - "98-additional_resources.Rmd"
    
bibliography: "references.bib"
number-depth: 0
format:
  html:
    theme: 
      light: flatly
      dark: superhero
    number-sections: false
    grid:
      sidebar-width: 350px
execute: 
  warning: false
  message: false

metadata-files:
  - _revealjs.yml
