project:
  type: book
  output-dir: docs


book:
  title: "Analysis of Ecological Data"
  author: "Marvin Ludwig"
  chapters:
    - "index.Rmd"
    - part: "Data"
      chapters:
      - "D01_data_examples.Rmd"
      - "D02_aasee.Rmd"
      - "D03_project_setup.Rmd"
    - part: "R"
      chapters:
      - "R01_introduction.qmd"
      - "R02_basics.qmd"
      - "R03_vectors.qmd"
      - "R04_dataframes.qmd"
      - "R05_tidyverse.qmd"
      - "R06_strings.qmd"
      - "R07_lists.qmd"
      - "R08_formula.qmd"
      - "R09_linearmodels.qmd"
      - "R10_ggplot.qmd"
    - part: "Exercises"
      chapters:
      - "exercise/E01-variablen.Rmd"
      - "exercise/E02-vectors-dataframes.Rmd"
      - "exercise/E03-more-dataframes.Rmd"
      - "exercise/E04-tidyverse.Rmd"
      - "exercise/E05-kritischer-sauerstoff.Rmd"
      - "exercise/E06-feldfruechte-arthropoden.Rmd"
      - "exercise/E07-lm.Rmd"
      - "exercise/E08-biodiversity.Rmd"
  appendices:
  - "98-additional_resources.Rmd"
  - "references.qmd"
  favicon: "/home/marvin/images/pictogramms/ecoR.svg"
    
bibliography: "../../literature/zotero/references.bib"
number-depth: 0
format:
  html:
    theme: cosmo
    number-sections: false
execute: 
  warning: false
  message: false


