# R11: markdown

R studio is much more than a code editor for R. It supports a variety of programming languages, documentation formats and data types.
One if its most used and most powerful features is the creation of markdown documents with integrated R code. In fact, this entire course page is written in markdown within Rstudio and then [rendered as a website](https://quarto.org/docs/websites/). Depending on the Rstudio Version you are using the markdown system is a little bit different:

1. The latest version of Rstudio used `quarto`. "An open-source scientific and technical publishing system" [https://quarto.org/](https://quarto.org/)
2. Older versions use `rmarkdown`. [https://rmarkdown.rstudio.com/](https://rmarkdown.rstudio.com/)

Depending on the system you are using, the typical file ending for the markdown files are either `.qmd` or `.rmd`.

## What is markdown?

Markdown is a "language" to format text. There are dedicated symbols for different purposes.
For example, text between two * appear **bold**.

You can find a basic introduction here: [https://quarto.org/docs/authoring/markdown-basics.html](https://quarto.org/docs/authoring/markdown-basics.html)


## Using markdown in Rstudio

Simply go to `File - New File - Quarto Document...` or `File - New File - R Markdown...` to create a markdown file with some example code and work your way from there. Or if you want to jump right into markdown projects go to `New Project... - New Directory` and choose an appropriate Template (e.g. Quarto Homepage)





